ProyectoWeb/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('tienda/', include('tienda.urls')),  

    path('carro/', include('carro.urls')),  

    path('', include('ProyectoWebApp.urls')),

       
    
]

ProyectoWebApp/urls.py
from django.urls import path

from ProyectoWebApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   
    path('',views.home, name="Home"),
    
   
    
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [
   
   
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
   
    
]

tienda/urls.py
from django.urls import path

from .import views


urlpatterns = [
   
   
    path('',views.tienda, name="Tienda"),
   
    
]

ProyectoWebApp/models.py
from django.db import models

# Create your models here.

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField()
    stock = models.IntegerField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

  

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

ProyectoWebApp/views.py
from django.shortcuts import render, HttpResponse




# Create your views here.

def home(request):

   return render(request, "ProyectoWebApp/home.html")
    

carro/views.py
from django.shortcuts import render

from .carro import Carro

from tienda.models import Producto

from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Tienda")


def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto
#from carro.carro import Carro


# Create your views here.

def tienda(request):    
    
    #carro=Carro(request)
    productos=Producto.objects.all()

    return render(request, "tienda/tienda.html", {"productos":productos})

ProyectoWebApp/templates/ProyectoWebApp/base.html
<html>

<head>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'ProyectoWebApp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'ProyectoWebApp/css/gestion.css' %}" rel="stylesheet">
</head>

<body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Music Pro</span>
      </h1>


 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav"> 
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Home' %}">Music Pro</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/tienda/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Tienda' %}">Tienda</a>
          </li>         
        </ul>
      </div>
    </div>
  </nav>


   <!-- Contenido cambiante-->
   {% block content %}


   {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Music Pro 2021</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'ProyectoWebApp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ProyectoWebApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

ProyectoWebApp/templates/ProyectoWebApp/home.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'ProyectoWebApp/img/front.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta" style="background-color: rgb(64, 26, 8);">
      <div class="container">
        <div class="row">
        
          <div class="col-xl-9 mx-auto">
          
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 33 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier instrumento musical a la puerta de su casa o studio con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    {% endblock %}


    

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white; background-color: rgb(64, 26, 8);">

    <thead>
        <tr>

            <th colspan="3" class="text-center">

                Carro compras

            </th>

        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>



        </tr>


    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">

                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>

                        {{value.precio}} $

                    </td>

                </tr>

            {% endfor %}

        {% else %}
            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        Sin productos
                    </div>

                </td>

            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                Total: ${{importe_total_carro}} 


            </td>


        </tr>
    </tfoot>


</table>

tienda/templates/tienda/tienda.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container">

  <div style="float:right;">
  
     

    {% include "carro/widget.html" %}

    
  </div>


  <div class="row">

{% for producto in productos %}
    
    <div class="col-md-3">

    <div class="card" style="width: 100%; margin: 15px 15px;right: 50px";>

        <img src="{{producto.imagen.url}}" class="card-img-top">

        <div class="card-body" style="text-align: center;">

            <h7 class="card-title">{{producto.nombre}}</h7>

            <p class="card-text">{{producto.precio}}&nbsp;$</p>

            {% for producto in productos %}
              <p style="color: black; font-size:20px">stock: {{producto.stock}}</p>
            {% endfor %}


        </div> 
        
        <div class="card-footer text-center" style="height: 150px; width:-50px">
            <a href="{% url 'carro:agregar' producto.id %}"  class="btn btn-success" style="height: 100px; width:100px;font-size:11px;">Agregar al carro</a>
        </div>

    </div><!--card que se cierra-->
    
  </div>



{% endfor %}
  </div>
 
  
</div>

{% endblock %}